Feat/erc theming
catppuccin/emacs pull request #147
Opened 2024-05-07 00:22 UTC by LionyxML

2024-05-08 21:49 UTC, jtbx requested changes

2024-05-08 21:49 UTC, jtbx commented on catppuccin-theme.el
> +               (erc-button :inherit link)
You can remove these, they are unchanged from the original
```suggestion
```

2024-05-08 21:49 UTC, jtbx commented on catppuccin-theme.el
> +               (erc-italic-face :slant italic)
```suggestion
```

2024-05-08 21:49 UTC, jtbx commented on catppuccin-theme.el
> +               (erc-error-face :foreground ,ctp-red :weight bold)
```suggestion
               (erc-error-face :foreground ,ctp-red)
```

2024-05-08 21:49 UTC, jtbx commented on catppuccin-theme.el
> +               (erc-prompt-face :foreground ,ctp-blue :weight bold)
This is duplication, the weight and slant of the face will be applied anyway
```suggestion
               (erc-keyword-face :foreground ,ctp-lavender)
               (erc-my-nick-face :foreground ,ctp-lavender)
               (erc-my-nick-prefix-face :foreground ,ctp-lavender)
               (erc-nick-default-face :foreground ,ctp-blue)
               (erc-nick-prefix-face :foreground ,ctp-blue)
               (erc-nick-msg-face :foreground ,ctp-yellow)
               (erc-notice-face :foreground ,ctp-subtext0)
               (erc-pal-face :foreground ,ctp-pink)
               (erc-prompt-face :foreground ,ctp-blue)
```

2024-05-08 21:49 UTC, jtbx commented on catppuccin-theme.el
> +               (erc-timestamp-face :foreground ,ctp-teal)
These faces are used for colour code highlighting, these were the colours I used
```suggestion
               (erc-timestamp-face :foreground ,ctp-teal)
               (bg:erc-color-face0 :background ,ctp-text)
               (bg:erc-color-face1 :background ,ctp-crust)
               (bg:erc-color-face2 :background ,ctp-blue)
               (bg:erc-color-face3 :background ,ctp-green)
               (bg:erc-color-face4 :background ,ctp-red)
               (bg:erc-color-face5 :background ,ctp-maroon)
               (bg:erc-color-face6 :background ,ctp-mauve)
               (bg:erc-color-face7 :background ,ctp-peach)
               (bg:erc-color-face8 :background ,ctp-yellow)
               (bg:erc-color-face9 :background ,ctp-green)
               (bg:erc-color-face10 :background ,ctp-lavender)
               (bg:erc-color-face11 :background ,ctp-teal)
               (bg:erc-color-face12 :background ,ctp-sapphire)
               (bg:erc-color-face13 :background ,ctp-pink)
               (bg:erc-color-face14 :background ,ctp-overlay2)
               (bg:erc-color-face15 :background ,ctp-text)
               (fg:erc-color-face0 :foreground ,ctp-text)
               (fg:erc-color-face1 :foreground ,ctp-crust)
               (fg:erc-color-face2 :foreground ,ctp-blue)
               (fg:erc-color-face3 :foreground ,ctp-green)
               (fg:erc-color-face4 :foreground ,ctp-red)
               (fg:erc-color-face5 :foreground ,ctp-maroon)
               (fg:erc-color-face6 :foreground ,ctp-mauve)
               (fg:erc-color-face7 :foreground ,ctp-peach)
               (fg:erc-color-face8 :foreground ,ctp-yellow)
               (fg:erc-color-face9 :foreground ,ctp-green)
               (fg:erc-color-face10 :foreground ,ctp-lavender)
               (fg:erc-color-face11 :foreground ,ctp-teal)
               (fg:erc-color-face12 :foreground ,ctp-sapphire)
               (fg:erc-color-face13 :foreground ,ctp-pink)
               (fg:erc-color-face14 :foreground ,ctp-overlay2)
               (fg:erc-color-face15 :foreground ,ctp-text)
```
Now if you look in `M-x customize-group erc-faces` you'll see that all erc faces are themed.

2024-05-09 23:05 UTC, jtbx approved these changes
Looks good thanks. It would be awesome if you could squash the 5 commits into one to remove the rubbish github added after that review. :smile:

2024-05-09 23:12 UTC, LionyxML commented
Thanks @jtbx!

2024-05-09 23:32 UTC, LionyxML commented
@jtbx looks like "I did it" :)

2024-05-09 23:37 UTC, jtbx commented
Awesome thanks a lot. :)

2024-06-04 18:55 UTC, NamesCode commented
Sorry for being so late to this. It looks amazing, thanks ^^

2024-06-04 18:55 UTC, merged